// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6JVLozqNIQI4AMXs-Fk7wS_YAszkrBU',
    appId: '1:585845477276:web:844211d27dcb9ad2654259',
    messagingSenderId: '585845477276',
    projectId: 'gym-rat-33695',
    authDomain: 'gym-rat-33695.firebaseapp.com',
    storageBucket: 'gym-rat-33695.firebasestorage.app',
    measurementId: 'G-SB5ZKGNSJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5yGjyzZcHYblvrq_vGfAqKGZchlwhbpo',
    appId: '1:585845477276:android:0fca365d99357f59654259',
    messagingSenderId: '585845477276',
    projectId: 'gym-rat-33695',
    storageBucket: 'gym-rat-33695.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfifVpjsEXRxJ2KE2u6Eo_0hRatEs38GA',
    appId: '1:585845477276:ios:a635df67aaef5265654259',
    messagingSenderId: '585845477276',
    projectId: 'gym-rat-33695',
    storageBucket: 'gym-rat-33695.firebasestorage.app',
    iosBundleId: 'com.example.gymSupplementsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfifVpjsEXRxJ2KE2u6Eo_0hRatEs38GA',
    appId: '1:585845477276:ios:a635df67aaef5265654259',
    messagingSenderId: '585845477276',
    projectId: 'gym-rat-33695',
    storageBucket: 'gym-rat-33695.firebasestorage.app',
    iosBundleId: 'com.example.gymSupplementsApp',
  );
}
